import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navber from './components/Navbar'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col items-center min-h-screen pt-3 px-10 gap-3 ${inter.className}`}
      >
        <Navber />
        <main style={{ width: '100%' }}>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
